---
title: Deborah Saks
timezone: America/Guyana
collections:
  pieces:
    title: Pieces
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Collages by Deborah
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
